---
- name: Create a managed Azure Container Services (AKS) cluster
  azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      kubernetes_version: "1.14.6"
      linux_profile:
          admin_username: "{{ username }}"
          ssh_key: "{{ ssh_key }}"
      service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_D2_v2
          vnet_subnet_id: "{{ vnet_subnet_id }}"
      network_profile:
          network_plugin: azure
          docker_bridge_cidr: 172.17.0.1/16
          dns_service_ip: 10.2.0.10
          service_cidr: 10.2.0.0/24
      tags:
          Environment: Production
  register: aks
