- name: Create an azure container registry
  azure_rm_containerregistry:
    name: "{{ acr_name }}" 
    location: "{{ location }}"
    resource_group: "{{ resource_group }}" 
    admin_user_enabled: true
    sku: "{{ acr_sku }}"
    tags:
        Release: beta1
        Environment: Production
